version: "3"
services:
  db:
    image: timescale/timescaledb:2.1.1-pg12
    ports:
      - 5432:5432
    volumes:
      - ./docker-entrypoint-initdb.sh:/docker-entrypoint-initdb.d/docker-entrypoint-initdb.sh
    environment:
      POSTGRES_DB: nomocms
      POSTGRES_USER: nomocms
      POSTGRES_PASSWORD: nomocms
